# Generated by Django 4.1.7 on 2023-10-25 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("managers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="allowed",
        ),
    ]
