# Generated by Django 4.1.7 on 2023-10-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managers", "0002_remove_permission_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="allowed",
            field=models.BooleanField(default=False),
        ),
    ]
