# Generated by Django 4.2.7 on 2023-11-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0002_deposittype_alter_deposits_deposit_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
