# Generated by Django 4.2.7 on 2023-11-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0005_tellervault_date_assigned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tellervault",
            name="vault",
        ),
        migrations.AddField(
            model_name="tellervault",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
