# Generated by Django 4.2.7 on 2023-11-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customers_image"),
        ("accounts", "0002_accounts_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="accounts",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="customers.customers"
            ),
        ),
    ]
