# Generated by Django 4.2.7 on 2023-11-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customers_image"),
        ("accounts", "0003_accounts_id_alter_accounts_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customers.customers"
            ),
        ),
    ]
