# Generated by Django 4.1.7 on 2023-10-25 14:36

from django.db import migrations, models
import managers.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_id",
                    models.CharField(
                        blank=True,
                        default=managers.utils.generate_profile_id,
                        max_length=255,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ghana_card_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("occupation", models.CharField(blank=True, max_length=255, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "postal_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[("SINGLE", "Single"), ("MARRIED", "Married")],
                        default="SINGLE",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        default="MALE",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "next_of_kin_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "next_of_kin_phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "next_of_kin_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "next_of_kin_relationship",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "is_approved",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APPROVED", "Approved"),
                            ("PENDING", "Pending"),
                            ("SUSPENDED", "Suspended"),
                            ("DEACTIVATED", "Deactivated"),
                        ],
                        default="PENDING",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
