# Generated by Django 4.1.7 on 2023-11-01 10:05

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_customers_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customers",
            name="image",
            field=models.ImageField(
                null=True, upload_to=customers.models.user_image_file_path
            ),
        ),
    ]
